#Postgresql

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: kloudcatch_development
  pool: 5
  username: my_user
  password: my_password

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: kloudcatch_test
  pool: 5
  username: my_user
  password: my_password

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: kloudcatch_production
  pool: 5
  username: my_user
  password: my_password
